/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define YY_USES_REJECT
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 83
#define YY_END_OF_BUFFER 84
static yyconst short int yy_acclist[474] =
    {   0,
    16460,16460,   84,   83,   81,   83,   19,   82,   83,   83,
    16460,   78,   83,   83,16460,   66,   83,   77,   83,   17,
       83,   18,   83,   10,   83,    8,   83,   80,   83,16460,
        9,   83,   11,   83,   74,   75,   83,16460,   63,   83,
       83,16460,   57,   83,   12,   83,   60,   83,   72, 8268,
       83,   72, 8268,   83,   72, 8268,   83,   64,   83,   65,
       83,   72, 8268,   83,   72, 8268,   83,   72, 8268,   83,
       72, 8268,   83,   72, 8268,   83,   72, 8268,   83,   72,
     8268,   83,   72, 8268,   83,   72, 8268,   83,   72, 8268,
       83,   72, 8268,   83,   72, 8268,   83,   72, 8268,   83,

       72, 8268,   83,   72, 8268,   83,   72, 8268,   83,   72,
     8268,   83,   72, 8268,   83,16460,   62, 8268,   73,    1,
    16460, 8268,   73,   79,   15,   13,   16,   14,   74,   75,
    16460, 8268,   58,   61,   59,   72, 8268,   72, 8268,   72,
     8268,   72, 8268,   29,   72, 8268,   72, 8268,   72, 8268,
       72, 8268,   72, 8268,   72, 8268,   72, 8268,   72, 8268,
       72, 8268,   72, 8268,   72, 8268,   72, 8268,   72, 8268,
       72, 8268,    3,   34,   72, 8268,   72, 8268,   23,   72,
     8268,   49,   72, 8268,   72, 8268,   72, 8268,   72, 8268,
       72, 8268,   20,   72, 8268,   72, 8268,   72, 8268,   72,

     8268,   72, 8268,   72, 8268,   72, 8268,   72, 8268,   72,
     8268,   72, 8268, 8268, 8268,   73,   73,   75,   75, 8268,
       72, 8268,   72, 8268,   21,   72, 8268,   72, 8268,   72,
     8268,   72, 8268,   72, 8268,   72, 8268,   72, 8268,   72,
     8268,   72, 8268,   37,   72, 8268,   31,   72, 8268,   72,
     8268,   72, 8268,   68,   72, 8268,   72, 8268,   72, 8268,
       30,   72, 8268,   72, 8268,   72, 8268,   72, 8268,   72,
     8268,   72, 8268,   72, 8268,   72, 8268,   22,   72, 8268,
       72, 8268,   72, 8268,   72, 8268,   72, 8268,   72, 8268,
       67,   72, 8268,   54,   72, 8268,   72, 8268,   72, 8268,

       72, 8268,   73,   75,   72, 8268,    6,   35,   72, 8268,
       72, 8268,   72, 8268,   72, 8268,   72, 8268,   48,   72,
     8268,   72, 8268,   72, 8268,   72, 8268,   33,   72, 8268,
        4,   72, 8268,   72, 8268,   72, 8268,   43,   72, 8268,
       72, 8268,   72, 8268,   72, 8268,   71,   72, 8268,   72,
     8268,   45,   72, 8268,   72, 8268,   40,   72, 8268,   72,
     8268,   72, 8268,   72, 8268,   72, 8268,   72, 8268,   52,
       72, 8268,   72, 8268,   73,    7,   36,   72, 8268,   72,
     8268,   46,   72, 8268,   53,   72, 8268,   50,   72, 8268,
       47,   72, 8268,   72, 8268,   72, 8268,   72, 8268,   72,

     8268,   72, 8268,   72, 8268,   72, 8268,   55,   72, 8268,
       72, 8268,   69,   72, 8268,   51,   72, 8268,   70,   72,
     8268,   72, 8268,    5,   72, 8268,   26,   72, 8268,    2,
       73,   42,   72, 8268,   72, 8268,   44,   72, 8268,   56,
       72, 8268,   72, 8268,   25,   72, 8268,   27,   72, 8268,
       41,   72, 8268,   72, 8268,   24,   28,   72, 8268,    2,
       72, 8268,   39,   72, 8268,   72, 8268,   38,   72, 8268,
       32,   72, 8268
    } ;

static yyconst short int yy_accept[232] =
    {   0,
        1,    2,    3,    4,    5,    7,   10,   12,   14,   16,
       18,   20,   22,   24,   26,   28,   31,   33,   35,   39,
       41,   43,   45,   47,   49,   52,   55,   58,   60,   62,
       65,   68,   71,   74,   77,   80,   83,   86,   89,   92,
       95,   98,  101,  104,  107,  110,  113,  116,  117,  118,
      119,  119,  120,  120,  121,  122,  123,  123,  124,  125,
      126,  127,  128,  129,  129,  132,  133,  134,  135,  136,
      138,  140,  142,  144,  147,  149,  151,  153,  155,  157,
      159,  161,  163,  165,  167,  169,  171,  173,  177,  179,
      182,  185,  187,  189,  191,  193,  196,  198,  200,  202,

      204,  206,  208,  210,  212,  214,  215,  216,  217,  218,
      219,  219,  221,  223,  225,  228,  230,  232,  234,  236,
      238,  240,  242,  244,  247,  250,  252,  254,  257,  259,
      261,  264,  266,  268,  270,  272,  274,  276,  278,  281,
      283,  285,  287,  289,  291,  294,  297,  299,  301,  303,
      303,  303,  304,  304,  305,  307,  311,  313,  315,  317,
      319,  322,  324,  326,  328,  331,  334,  336,  338,  341,
      343,  345,  347,  350,  352,  355,  357,  357,  360,  362,
      364,  366,  368,  370,  373,  375,  375,  375,  376,  380,
      382,  385,  388,  391,  394,  396,  398,  400,  402,  404,

      406,  408,  411,  413,  413,  416,  419,  422,  424,  427,
      430,  430,  432,  435,  437,  440,  443,  445,  448,  451,
      454,  456,  457,  460,  461,  463,  466,  468,  471,  474,
      474
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    7,    1,    8,    1,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    1,   20,   24,   24,   24,   24,   25,   26,
       24,   24,   24,   24,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   27,   24,   24,   24,   24,   24,   24,
       28,    1,   29,    1,   30,    1,   31,   32,   33,   34,

       35,   36,   37,   38,   39,   24,   40,   41,   42,   43,
       44,   45,   24,   46,   47,   48,   49,   24,   50,   51,
       52,   24,    1,   53,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[54] =
    {   0,
        1,    1,    2,    1,    3,    1,    3,    1,    1,    1,
        1,    1,    1,    3,    1,    1,    1,    4,    1,    3,
        1,    3,    1,    4,    4,    4,    4,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    1
    } ;

static yyconst short int yy_base[239] =
    {   0,
        0,    0,  403,  404,  404,  404,   49,  396,   71,  404,
      392,  404,  404,   43,  378,  120,  377,  376,  138,  404,
      112,  375,  374,  373,    0,  363,  347,  404,  404,   14,
      346,   95,  356,   17,  102,  349,  108,   31,  358,  344,
      341,  118,   98,  351,  339,   93,  345,  141,  404,    0,
      377,  376,  378,  404,    0,  176,  371,  370,  404,  404,
      404,  404,  404,  360,    0,  217,  404,  404,  404,    0,
      336,  327,  341,  115,  343,  338,  325,  340,  327,  134,
      114,  335,  323,  324,  320,  321,  320,    0,  318,    0,
        0,  320,  314,  312,  126,    0,  312,  319,  194,  309,

      311,  303,  315,  305,  317,    0,    0,  342,  162,  213,
      332,  331,  301,  312,    0,  311,  302,  305,  312,  307,
      294,  292,  304,    0,    0,  302,  302,    0,  301,  304,
        0,  292,  301,  288,  299,  282,  296,  199,  324,  280,
      283,  278,  287,  274,    0,    0,  281,  283,  279,  233,
      236,  238,  231,  301,  283,    0,  271,  283,  267,  274,
        0,  266,  273,  268,    0,    0,  277,  268,    0,  277,
      261,  258,    0,  250,    0,  239,  243,    0,  233,  245,
      244,  232,  242,    0,  242,  247,  248,  249,    0,  227,
        0,    0,    0,    0,  231,  225,  224,  230,  228,  220,

      236,    0,  233,  222,    0,    0,    0,  221,    0,    0,
      250,  251,    0,  214,    0,    0,  210,    0,    0,    0,
      212,  404,    0,  252,  137,    0,   94,    0,    0,  404,
      282,  286,  290,   62,   55,  294,  298,  302
    } ;

static yyconst short int yy_def[239] =
    {   0,
      230,    1,  230,  230,  230,  230,  231,  232,  230,  230,
      233,  230,  230,  230,  230,  231,  230,  230,  231,  230,
       19,  230,  230,  230,  234,  234,  234,  230,  230,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,   19,  230,  235,
      232,  232,  236,  230,    9,  230,  233,  233,  230,  230,
      230,  230,  230,  230,   19,  235,  230,  230,  230,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,

      234,  234,  234,  234,  234,  235,   56,  233,  237,  230,
      230,  235,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  237,
      238,  237,  230,  230,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  234,  234,  234,  234,  234,  230,  234,  234,  234,
      234,  234,  234,  234,  234,  238,  238,  237,  234,  234,
      234,  234,  234,  234,  234,  234,  234,  234,  234,  234,

      234,  234,  234,  230,  234,  234,  234,  234,  234,  234,
      238,  237,  234,  234,  234,  234,  234,  234,  234,  234,
      234,  230,  234,  238,  234,  234,  234,  234,  234,    0,
      230,  230,  230,  230,  230,  230,  230,  230
    } ;

static yyconst short int yy_nxt[458] =
    {   0,
        4,    5,    6,    4,    7,    8,    9,   10,   11,   12,
       13,   14,   15,   16,   17,    4,   18,   19,   20,   21,
       22,   23,   24,   25,   25,   26,   27,   28,   29,   25,
       30,   31,   32,   33,   34,   35,   36,   25,   37,   25,
       38,   39,   40,   41,   42,   43,   44,   45,   25,   46,
       25,   47,    4,   48,   59,   48,   73,   81,  106,   82,
       74,   92,   48,   75,   60,   70,   48,   83,   48,   93,
       49,   53,   53,   54,   53,   55,   53,   55,   53,   53,
       53,   53,   53,   53,   55,   53,   53,   53,   55,   53,
       55,   53,   53,   53,   56,   56,   56,   56,   53,   53,

       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   53,   48,   77,   48,  230,   99,   48,
      103,  104,  100,   48,  229,   78,   50,   48,   79,   48,
       84,  230,   48,   88,   48,   85,   50,   86,   97,   89,
       90,   48,  126,   64,   91,   65,  230,   48,   48,  230,
      127,  116,   66,   98,  151,   50,  117,  123,  138,  124,
      152,  228,   66,  139,  125,   50,   53,   53,   54,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,  107,   53,   53,   53,   53,   53,  107,

      107,  107,  107,   53,   53,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,  107,  107,
      107,  107,  107,  107,  107,  107,  107,  107,   53,  111,
      110,  111,  142,  175,  112,  151,  143,  153,  151,  176,
      151,  152,  227,  111,  187,  111,  188,  153,  154,  151,
      151,  151,  151,  151,  151,  187,  211,  212,  224,  212,
      224,  226,  225,  223,  222,  221,  220,  219,  218,  111,
      217,  216,  215,  214,  213,  210,  209,  208,  207,  206,
      205,  204,  203,  111,   50,   50,   51,  202,   51,   51,
       57,  201,   57,   57,   53,   53,   53,   53,  150,  150,

      150,  150,  186,  186,  186,  186,  200,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  154,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  174,  173,
      172,  171,  170,  169,  168,  167,  166,  165,  164,  163,
      162,  161,  160,  159,  158,  157,  156,  155,  112,  154,
      108,  149,  148,  147,  146,  145,  144,  141,  140,  137,
      136,  135,  134,  133,  132,  131,  130,  129,  128,  122,
      121,  120,  119,  118,  115,  114,  113,  110,  109,  108,
       54,   52,   52,  105,  102,  101,   96,   95,   94,   87,
       80,   76,   72,   71,   69,   68,   67,   63,   62,   61,

       58,   52,  230,    3,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230
    } ;

static yyconst short int yy_chk[458] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    7,   14,    7,   30,   34,  235,   34,
       30,   38,    7,   30,   14,  234,    7,   34,    7,   38,
        7,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,   16,   32,   16,   21,   43,   21,
       46,   46,   43,   16,  227,   32,   21,   16,   32,   16,
       35,   16,   19,   37,   19,   35,   21,   35,   42,   37,
       37,   19,   81,   19,   37,   19,   48,   19,   48,   19,
       81,   74,   19,   42,  109,   48,   74,   80,   95,   80,
      109,  225,   19,   95,   80,   48,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,

       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   56,
       56,   56,   56,   56,   56,   56,   56,   56,   56,   66,
      110,   66,   99,  138,   66,  150,   99,  110,  151,  138,
      152,  150,  221,  153,  151,  153,  152,  110,  153,  186,
      187,  188,  211,  212,  224,  186,  187,  188,  211,  212,
      224,  217,  214,  208,  204,  203,  201,  200,  199,   66,
      198,  197,  196,  195,  190,  185,  183,  182,  181,  180,
      179,  177,  176,  153,  231,  231,  232,  174,  232,  232,
      233,  172,  233,  233,  236,  236,  236,  236,  237,  237,

      237,  237,  238,  238,  238,  238,  171,  170,  168,  167,
      164,  163,  162,  160,  159,  158,  157,  155,  154,  149,
      148,  147,  144,  143,  142,  141,  140,  139,  137,  136,
      135,  134,  133,  132,  130,  129,  127,  126,  123,  122,
      121,  120,  119,  118,  117,  116,  114,  113,  112,  111,
      108,  105,  104,  103,  102,  101,  100,   98,   97,   94,
       93,   92,   89,   87,   86,   85,   84,   83,   82,   79,
       78,   77,   76,   75,   73,   72,   71,   64,   58,   57,
       53,   52,   51,   47,   45,   44,   41,   40,   39,   36,
       33,   31,   27,   26,   24,   23,   22,   18,   17,   15,

       11,    8,    3,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230,  230,  230,  230,
      230,  230,  230,  230,  230,  230,  230
    } ;

static yy_state_type yy_state_buf[YY_BUF_SIZE + 2], *yy_state_ptr;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */ \
yy_cp = yy_full_match; /* restore poss. backed-over text */ \
yy_lp = yy_full_lp; /* restore orig. accepting pos. */ \
yy_state_ptr = yy_full_state; /* restore orig. state */ \
yy_current_state = *yy_state_ptr; /* restore curr. state */ \
++yy_lp; \
goto find_rule; \
}
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "pylexer.l"
#define INITIAL 0
#line 19 "pylexer.l"
#include<stdio.h>
#include"y.tab.h"
#include<string.h>
extern YYSTYPE yylval;
int t = 1;
int n = 0;
#line 617 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 27 "pylexer.l"

#line 770 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_state_ptr = yy_state_buf;
		*yy_state_ptr++ = yy_current_state;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 231 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			*yy_state_ptr++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 404 );

yy_find_action:
		yy_current_state = *--yy_state_ptr;
		yy_lp = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( yy_lp && yy_lp < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[yy_lp];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     yy_looking_for_trail_begin )
					{
					if ( yy_act == yy_looking_for_trail_begin )
						{
						yy_looking_for_trail_begin = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					yy_looking_for_trail_begin = yy_act & ~YY_TRAILING_MASK;
					yy_looking_for_trail_begin |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					yy_full_match = yy_cp;
					yy_full_state = yy_state_ptr;
					yy_full_lp = yy_lp;
					break;
					}
				++yy_lp;
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--yy_state_ptr;
			yy_lp = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 28 "pylexer.l"
{printf("comment ");return COMMENT;} 
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 29 "pylexer.l"
{printf("comment ");return COMMENT;} 
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "pylexer.l"
{printf("if ");return IF;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "pylexer.l"
{printf("else ");return ELSE;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "pylexer.l"
{printf("while ");return WHILE;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "pylexer.l"
{printf("True ");yylval=strdup(yytext);return T;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "pylexer.l"
{printf("False ");yylval=strdup(yytext);return F;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "pylexer.l"
{printf("plus ");yylval=strdup(yytext);return PLUS;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "pylexer.l"
{printf("minus ");return MINUS;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "pylexer.l"
{printf("mul ");return MUL;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "pylexer.l"
{printf("divide ");return DIVIDE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "pylexer.l"
{printf("equal ");return EQUAL;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "pylexer.l"
{printf("plusequal ");return PLUSEQUAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "pylexer.l"
{printf("divideequal ");return DIVIDEEQUAL;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "pylexer.l"
{printf("mulequal ");return MULEQUAL;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "pylexer.l"
{printf("minusequal ");return MINUSEQUAL;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "pylexer.l"
{printf("special_start ");return SPECIAL_START;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "pylexer.l"
{printf("special_end ");return SPECIAL_END;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "pylexer.l"
{printf("\n");return NL;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "pylexer.l"
{printf("or ");return OR;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "pylexer.l"
{printf("and ");return AND;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "pylexer.l"
{printf("not ");return NOT;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "pylexer.l"
{printf("in ");return IN;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "pylexer.l"
{printf("not in ");return NOTIN;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 54 "pylexer.l"
{printf("global"); return GLOBAL;}                     
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 55 "pylexer.l"
{printf("yield"); return YIELD;}   
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 56 "pylexer.l"
{printf("import"); return IMPORT;}   
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 57 "pylexer.l"
{printf("return"); return RETURN;}    
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 58 "pylexer.l"
{printf("as"); return AS;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 59 "pylexer.l"
{printf("for"); return FOR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 60 "pylexer.l"
{printf("del"); return DEL;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 61 "pylexer.l"
{printf("nonlocal"); return NONLOCAL;}       
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 62 "pylexer.l"
{printf("elif"); return ELIF;}   
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 63 "pylexer.l"
{printf("if"); return IF;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 64 "pylexer.l"
{printf("True"); return TRUE;}   
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 65 "pylexer.l"
{printf("False"); return FALSE;}   
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 66 "pylexer.l"
{printf("def"); return DEF;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 67 "pylexer.l"
{printf("continue"); return CONTINUE;}       
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 68 "pylexer.l"
{printf("finally"); return FINALLY;}   
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 69 "pylexer.l"
{printf("pass"); return PASS;}   
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 70 "pylexer.l"
{printf("lambda"); return LAMBDA;}   
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 71 "pylexer.l"
{printf("assert"); return ASSERT;}   
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 72 "pylexer.l"
{printf("from"); return FROM;}   
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 73 "pylexer.l"
{printf("dedent"); return DEDENT;}   
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 74 "pylexer.l"
{printf("none"); return NONE;}   
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 75 "pylexer.l"
{printf("async"); return ASYNC;}   
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 76 "pylexer.l"
{printf("class"); return CLASS;}   
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 77 "pylexer.l"
{printf("case"); return CASE;}    
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 78 "pylexer.l"
{printf("is"); return IS;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 79 "pylexer.l"
{printf("break"); return BREAK;}   
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 80 "pylexer.l"
{printf("raise"); return RAISE;}   
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 81 "pylexer.l"
{printf("with"); return WITH;}   
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 82 "pylexer.l"
{printf("await"); return AWAIT;}    
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 83 "pylexer.l"
{printf("try"); return TRY;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 84 "pylexer.l"
{printf("match"); return MATCH;}   
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 85 "pylexer.l"
{printf("expect"); return EXPECT;}    
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 87 "pylexer.l"
{printf("lessthan ");return LESSTHAN;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 88 "pylexer.l"
{printf("lessthanequal ");return LESSTHANEQUAL;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 89 "pylexer.l"
{printf("greaterthanequal ");return GREATERTHANEQUAL;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 90 "pylexer.l"
{printf("greaterthan ");return GREATERTHAN;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 91 "pylexer.l"
{printf("doubleequal ");return DOUBLEEQUAL;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 92 "pylexer.l"
{printf("notequal ");return NOTEQUAL;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 93 "pylexer.l"
{printf("colon ");return COLON;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 94 "pylexer.l"
{printf("sq bracket start ");return SQUAREBRACKET_START;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 95 "pylexer.l"
{printf("sq bracket end ");return SQUAREBRACKET_END;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 96 "pylexer.l"
{printf("mod ");return MOD;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 97 "pylexer.l"
{printf("sep ");return SEP;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 98 "pylexer.l"
{printf("end" );return END;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 99 "pylexer.l"
{printf("print ");return PRINT;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 100 "pylexer.l"
{printf("range ");return RANGE;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 101 "pylexer.l"
{printf("list ");return LIST;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 102 "pylexer.l"
{printf("ID ");yylval=strdup(yytext);return NAME;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 103 "pylexer.l"
{printf("string ");yylval=strdup(yytext);return STRING;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 104 "pylexer.l"
{printf("int ");yylval=strdup(yytext);return INTEGER;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 105 "pylexer.l"
{printf("num ");yylval=strdup(yytext);return NUM;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 106 "pylexer.l"
{printf("%s\t",yytext);}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 107 "pylexer.l"
{printf("single quote ");return SINGLEQUOTE;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 108 "pylexer.l"
{printf("double quote ");return DOUBLEQUOTE;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 109 "pylexer.l"
{printf("exp ");return EXPONENTIAL;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 110 "pylexer.l"
{printf("comma ");return COMMA;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 111 "pylexer.l"
{printf("indent ");return INDENT;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 112 "pylexer.l"
{printf("newline"); return NEWLINE;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 114 "pylexer.l"
ECHO;
	YY_BREAK
#line 1289 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_state_ptr = yy_state_buf;
	*yy_state_ptr++ = yy_current_state;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 231 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		*yy_state_ptr++ = yy_current_state;
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;

	register YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 231 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 230);
	if ( ! yy_is_jam )
		*yy_state_ptr++ = yy_current_state;

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 114 "pylexer.l"


int yywrap() {
    return 1;
}